const REACT_QUERY_KEYS = {
  DASHBOARD: {
    GET_SUMMARY: 'GET_SUMMARY',
    GET_CLASS: 'GET_CLASS',
    GET_NEW_CLASS: 'GET_NEW_CLASS',
    GET_REVENUE: 'GET_REVENUE',
    GET_SCHEDULE: 'GET_SCHEDULE',
    GET_LEARN_ACTIVITY: 'GET_LEARN_ACTIVITY',
  },
};

export default REACT_QUERY_KEYS;
